use std::io::Write;

use super::*;

impl AssemblyScriptGenerator {
    pub fn header<T: Write>(&self, w: &mut PrettyWriter<T>) -> Result<(), Error> {
        w.write_lines(
            "
/*
 * This file was automatically generated by witx-codegen - Do not edit manually.
 */",
        )?;
        if self.typescript_mode {
            w.write_lines(
                "
// Pointer to target
export type ptr<T> = number & { _pointerTarget: T };
// Mutable pointer to target
export type mutptr<T> = ptr<T>;

// Type Definition for complex and simple types
export interface TypeDef<T> {
    size: number;
    align: number;
    
    get(buf: ArrayBuffer, ptr: ptr<T>): T;
    set(buf: ArrayBuffer, ptr: ptr<T>, value: T): void;
}
// Get target JS type of TypeDef
export type TargetType<D> = D extends TypeDef<infer T> ? T : never;
    
const getDataView = (() => {
    const cache = new WeakMap<ArrayBuffer, DataView>();
    
    return (buf: ArrayBuffer) => {
        let dataView = cache.get(buf);
        if (!dataView) {
        dataView = new DataView(buf);
        cache.set(buf, dataView);
        }
        return dataView;
    };
})();

// Function to get TypeDef for primitive JS types
function std<T = number>(name: string, size: number): TypeDef<T> {
    const get = (DataView.prototype as any)[`get${name}`];
    const set = (DataView.prototype as any)[`set${name}`];

    return {
        size,
        align: size,
        get(buf, ptr) {
            return get.call(getDataView(buf), ptr, true);
        },
        set(buf, ptr, value) {
            return set.call(getDataView(buf), ptr, value, true);
        },
    };
}

// Function for UTF-8 strings
export const string = (() => {
  const textEncoder = new TextEncoder();
  const textDecoder = new TextDecoder();

  return {
    get(buf: ArrayBuffer, ptr: ptr<string>, len: number): string {
      return textDecoder.decode(new Uint8Array(buf, ptr, len));
    },
    set(
      buf: ArrayBuffer,
      ptr: ptr<string>,
      value: string,
      len?: number | undefined
    ) {
      if (len) {
        const { read } = textEncoder.encodeInto(
          value,
          new Uint8Array(buf, ptr, len)
        );
        if (read! < value.length) {
          throw new Error(`Insufficient space.`);
        }
      } else {
        // we don't know the string length beforehand
        const src = textEncoder.encode(value);
        len = src.byteLength;
        const dst = new Uint8Array(buf, ptr, len);
        dst.set(src);
      }
    },
  };
})();
  
function alignTo(ptr: number, align: number): number {
  const mismatch = ptr % align;
  if (mismatch) {
    ptr += align - mismatch;
  }
  return ptr;
}
  
// To construct TypeDef for structs
export function struct<T extends Record<string, TypeDef<any>>>(
  desc: T
): TypeDef<{ [K in keyof T]: T[K] extends TypeDef<infer F> ? F : never }> {
  class Ctor {
    constructor(protected _buf: ArrayBuffer, protected _ptr: number) {}
  }
  let offset = 0;
  let structAlign = 0;
  for (const name in desc) {
    const type = desc[name];
    const fieldAlign = type.align;
    structAlign = Math.max(structAlign, fieldAlign);
    offset = alignTo(offset, fieldAlign);
    const fieldOffset = offset;
    Object.defineProperty(Ctor.prototype, name, {
      get(this: Ctor) {
        return type.get(this._buf, (this._ptr + fieldOffset) as ptr<any>);
      },
      set(this: Ctor, value) {
        type.set(this._buf, (this._ptr + fieldOffset) as ptr<any>, value);
      },
    });
    offset += type.size;
  }
  offset = alignTo(offset, structAlign);
  return {
    size: offset,
    align: structAlign,
    get(buf, ptr) {
      return new Ctor(buf, ptr) as any;
    },
    set(buf, ptr, value) {
      Object.assign(new Ctor(buf, ptr), value);
    },
  };
}

// To construct TypeDef for taggedUnion
export function taggedUnion<
  E extends number,
  T extends Record<E, TypeDef<any>>
>({
  tag: tagDesc,
  data: dataDesc,
}: {
  tag: TypeDef<E>;
  data: T;
}): TypeDef<
  {
    [K in E]: { tag: K; data: T[K] extends TypeDef<infer F> ? F : never };
  }[E]
> {
  let unionSize = 0;
  let unionAlign = 0;
  for (const key in dataDesc) {
    const { size, align } = dataDesc[key];
    unionSize = Math.max(unionSize, size);
    unionAlign = Math.max(unionAlign, align);
  }
  unionSize = alignTo(unionSize, unionAlign);
  const unionOffset = alignTo(tagDesc.size, unionAlign);
  const totalAlign = Math.max(tagDesc.align, unionAlign);
  const totalSize = alignTo(unionOffset + unionSize, totalAlign);
  return {
    size: totalSize,
    align: totalAlign,
    get(buf, ptr) {
      const tag = tagDesc.get(buf, ptr as ptr<any>);
      return {
        tag,
        data: dataDesc[tag].get(buf, (ptr + unionOffset) as ptr<any>),
      };
    },
    set(buf, ptr, value) {
      tagDesc.set(buf, ptr as ptr<any>, value.tag);
      dataDesc[value.tag].set(buf, (ptr + unionOffset) as ptr<any>, value.data);
    },
  };
}

// To construct TypeDef for enum
export function enumer<E extends number>(base: TypeDef<number>): TypeDef<E> {
  // All the properties are same as for the underlying number, this wrapper is only useful at typechecking level.
  return base as TypeDef<E>;
}
",
            )?;
        }
        if self.typescript_mode {
            w.write_lines(
                "
export const i8 = std('Int8', 1);
export type i8 = number;
export const u8 = std('Uint8', 1);
export type u8 = number;
export const i16 = std('Int16', 2);
export type i16 = number;
export const u16 = std('Uint16', 2);
export type u16 = number;
export const i32 = std('Int32', 4);
export type i32 = number;
export const u32 = std('Uint32', 4);
export type u32 = number;
export const usize = std('Uint32', 4);
export type usize = number;
export const i64 = std<bigint>('bigint64', 8);
export type i64 = bigint;
export const u64 = std<bigint>('BigUint64', 8);
export type u64 = bigint;

    ",
            )?;
        }

        w.write_lines(
            "
export const Handle = i32;
export type Handle = TargetType<typeof Handle>;
export const Char8 = u8;
export type Char8 = TargetType<typeof Char8>;
export const Char32 = u32;
export type Char32 = TargetType<typeof Char32>;

export type WasiStringBytesPtr = ptr<Char8>;
",
        )?;
        if self.typescript_mode {
          w.write_lines(
            "
export type WasiMutSlice<T> = usize;
export type WasiSlice<T> = usize;
"
          )?
          .eob()?;
        } else {

        w.write_lines(
            "
export type ptr<T> = usize;
export type mutptr<T> = usize;            

// @ts-ignore: decorator
@unmanaged
export class WasiString {
    ptr: WasiStringBytesPtr;
    length: usize;

    constructor(str: string) {
        let wasiString = String.UTF8.encode(str, false);
        // @ts-ignore: cast
        this.ptr = changetype<WasiStringBytesPtr>(wasiString);
        this.length = wasiString.byteLength;
    }

    toString(): string {
        let tmp = new ArrayBuffer(this.length as u32);
        memory.copy(changetype<usize>(tmp), this.ptr, this.length);
        return String.UTF8.decode(tmp);
    }
}

// @ts-ignore: decorator
@unmanaged
export class WasiSlice<T> {
    ptr: ptr<T>;
    length: usize;

    constructor(array: ArrayBufferView) {
        // @ts-ignore: cast
        this.ptr = array.dataStart;
        this.length = array.byteLength;
    }
}

// @ts-ignore: decorator
@unmanaged
export class WasiMutSlice<T> {
    ptr: mutptr<T>;
    length: usize;

    constructor(array: ArrayBufferView) {
        // @ts-ignore: cast
        this.ptr = array.dataStart;
        this.length = array.byteLength;
    }
}
",
        )?
        .eob()?;
      }
      Ok(())
  }
}
