name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Run functional tests
        run: |
          cargo run -- --output-type=overview tests/*.witx > /dev/null
          cargo run -- --output-type=markdown tests/*.witx > /dev/null
          cargo run -- --output-type=assemblyscript tests/*.witx > /dev/null
          cargo run -- --output-type=zig tests/*.witx > /dev/null
          cargo run -- --output-type=rust tests/*.witx > /dev/null
      - name: Check that crates version works
        run: cargo install witx-docgen --debug
