name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - uses: hecrj/setup-rust-action@110f36749599534ca96628b82f52ae67e5d95a3c # master
        with:
          rust-version: stable

      - name: Check Cargo availability
        run: cargo --version

      - name: Check Rustup default toolchain
        run: rustup default | grep stable

      - name: Install cargo-deb
        run: cargo install --debug cargo-deb

      - name: Build
        run: |
          env RUSTFLAGS="-C link-arg=-s" cargo build --release
          mkdir witx-codegen
          mv target/release/witx-codegen witx-codegen/
          cp README.md witx-codegen/
          tar cJpf witx-codegen_${{ steps.get_version.outputs.VERSION }}_linux-x86_64.tar.bz2 witx-codegen
      - name: Debian package
        run: |
          cargo deb

      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Debian package
        id: upload-release-asset-debian
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: "witx-codegen_${{ steps.get_version.outputs.VERSION }}_amd64.deb"
          asset_path: "target/debian/witx-codegen_${{ steps.get_version.outputs.VERSION }}_amd64.deb"
          asset_content_type: application/x-debian-package

      - name: Upload tarball
        id: upload-release-asset-tarball
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: "witx-codegen_${{ steps.get_version.outputs.VERSION }}_linux-x86_64.tar.bz2"
          asset_path: "witx-codegen_${{ steps.get_version.outputs.VERSION }}_linux-x86_64.tar.bz2"
          asset_content_type: application/x-tar
